Add feature to pass extra args when pushing image
redhat-actions/push-to-registry pull request #19
Opened 2021-01-28 11:20 UTC by Divyansh42

If a user wants to pass few extra args to push
command when pushing image, then he can pass
using 'extra-args' input parameter.
This PR adds another input `extra-args` to pass extra arguments.

Fixes: #17 

Signed-off-by: divyansh42 <diagrawa@redhat.com>

2021-02-03 02:38 UTC, tetchel requested changes

2021-02-03 02:38 UTC, tetchel commented on README.md
> +    <td>Extra args to be passed to push command when pushing image.</td>
"to be passed to `podman push`."

2021-02-03 02:38 UTC, tetchel commented on action.yml
> +    description: 'Extra args to be passed to push command when pushing image'
update this one too (not that it matters)

2021-02-03 02:38 UTC, tetchel commented on src/index.ts
> +        args.push(extraArgs);
I think the extra-args may be best off split over newlines so the user doesn't have to quote them.

2021-02-05 00:36 UTC, tetchel commented
can you add some extra_args to a test case?

2021-02-07 14:43 UTC, Divyansh42 commented
Figured out that, [pull_request_target](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) is not running on the PR branch.
So here is the test workflow: https://github.com/Divyansh42/push-to-registry/runs/1849255706?check_suite_focus=true#step:10:110

2021-02-08 14:37 UTC, tetchel approved these changes

2021-02-08 14:37 UTC, merged