Add feature to push manifest
redhat-actions/push-to-registry pull request #55
Opened 2021-11-10 17:37 UTC by divyansh42

Signed-off-by: divyansh42 <diagrawa@redhat.com>

### Description
Manifest will be detected automatically by this action, no separate input is required for this feature.

### Related Issue(s)
Close #53 

### Checklist

- [x] This PR includes a documentation change
- [ ] This PR does not need a documentation change
---
- [x] This PR includes test changes
- [ ] This PR's changes are already tested
---
- [ ] This change is not user-facing
- [ ] This change is a patch change
- [x] This change is a minor change
- [ ] This change is a major (breaking) change

### Changes made

2021-11-10 17:38 UTC, divyansh42 commented
https://github.com/divyansh42/push-to-registry/actions/runs/1445395283 this workflow run describes manifest build and push

2021-11-11 02:35 UTC, tetchel requested changes

2021-11-11 02:35 UTC, tetchel commented on src/index.ts
> +    const isManifest = await checkIfManifestsExists();
log any images that are manifests

2021-11-11 02:35 UTC, tetchel commented on src/index.ts
> +async function checkIfManifestsExists(): Promise<boolean> {
If at least one manifest is found, log somewhere the list of images that are manifests

2021-11-11 02:35 UTC, tetchel commented on src/index.ts
> +    if (foundManifests.length > 0 && missingManifests.length > 0) {
So it is an error condition if some of the images are manifests, but not all of them ? is that the right behaviour? what if some are regular images?

2021-11-11 02:35 UTC, tetchel commented on src/index.ts
> +    if (missingManifests.length === sourceImages.length) {
I find this kind of confusing.

I would do `return foundManifests.length === sourceImages.length`.

2021-11-11 03:46 UTC, tetchel commented
Also needs a readme update

2021-11-11 19:22 UTC, tetchel commented on README.md
> +This action supports manifest, this means you can push the manifest with this action.
Please link to some buildah documentation explaining what manifests are

2021-11-15 03:35 UTC, tetchel commented on README.md
> +Push-to-registry is a GitHub Action for pushing a container image or a manifest to an image registry, such as Dockerhub, quay&#46;io, the GitHub Container Registry, or an OpenShift integrated registr
Needs explanation of what a manifest is (link to buildah doc)

2021-11-15 03:35 UTC, tetchel approved these changes

2021-11-17 12:00 UTC, merged